### ISSUE TITLE
chore: consider captcha

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/donate.keyman.com#103]
Some scammers trying to use this site for stolen cc validation. A captcha would probably be enough to block them. See if Stripe offers this as an opt (or other fraud prevention measures) before rolling our own.

**Comment by darcywong00** [comment]
Maybe this [plugin](https://s-plugins.com/stripe-payments-recaptcha-addon/)?

**Comment by mcdurdin** [comment]
Closing, site is now in redirect mode (#104) and will be replaced in the future.
